HOUSES_COUNT = 5
HAPPY_MIN = 10
HAPPY_MAX = 10
MAP_WIDTH = 600
MAP_HEIGHT = 400
GIFT_RANGE_SQUARE = 64**2
HOUSE_RANGE_SUARE = 64**2
REQUEST_INTERVAL_MS = 20
PLAYER_STEP = 25
#response strings
ALREADY_GIFTED='ALREADY_GIFTED'
SUCCESS='SUCCESS'
BAD_GIFT_POSITION='BAD_POSITION'
BAD_ID='BAD_PLAYER_ID'
REQUEST_REJECTED='REQUEST_REJECTED'
BAD_MOVE='BAD_MOVE_CODE'
#moving directions
UP='0'
DOWN='1'
LEFT='2'
RIGHT='3'