HOUSES_COUNT = 10
HAPPY_MIN = 1
HAPPY_MAX = 10
MAP_WIDTH = 400
MAP_HEIGHT = 400
GIFT_RANGE = 5.5
HOUSE_RANGE_SUARE = 7.2**2
#response strings
ALREADY_GIFTED='ALREADY_GIFTED'
SUCCESS='SUCCESS'
BAD_GIFT_POSITION='BAD_POSITION'